### ISSUE TITLE
[TASK] Grey Knight Codex Init

### ISSUE THREAD

**Issue by tekton** [BSData/wh40k#1115]
**File/Catalogue:** Imperium - Grey Knights

**NOTE**: This is a place for me to track updates since I've already started, I may or may not look at comments- if I don't respond it's not that I don't like you, it's that I've been working.

- [x] Grand Master in ND
- [x] (Converted) Chaplain
- [x] Power level re-align
- [x] Dreadnought Psyker Change
- [x] Make sure singular characters are singular
- [x] New psychic abilities
- [x] Warlord traits
- [x] Warlord trait UI
- [x] Warlord trait limitation
- [x] Storm* Fliers
- [x] Confirm points (once releases)

**Comment by akillthegod** [comment]
so?

**Comment by alphalas** [comment]
So what? This isn't going to even remotely go live until after the codex releases
