### ISSUE TITLE
Codex CSM Outstanding Issues rollup

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#1212]
**File/Catalogue:** Chaos Space Marines v25

**Description:**

- [x] Possessed should have two wounds
- [x] Psykers can't have Mark of Khorne
- [x] HQs should be restricted for incorrect Legions.
- [x] Emperor's Children can't have any Mark except Slaanesh
- [x] World Eaters can't have any Mark except Khorne
- [x] Add Daemon Troops
- [x] Fix Lasher tendrils ability
- [x] Fix Doom Siren profile
- [x] Chosen Champion weapon validation issue (c.f. #1224)
- [x] Defiler damage table incorrect (c.f. #1226)
- [x] Berzerker champion power fist cost incorrect (c.f. #1229)

**Comment by Izwor** [comment]
Bikers -6p
Cultists -1p
Lord Terminator -17p !!
Predator -12p
Vindicator -25p
Defiler -66p !!
Lord of Skulls -100p !!
Maulerfiend -9p
Mutilators -15p
Noise Marinse -1p
Plaguem Marines -2p
Warpsmith -30p !!
Abaddon -13p
Kharn -13p
Exalted Champion points as Lord but -4p

Baleflamer -30p
Blastmaster -8p
Hades Autocannon - 8p
Reaper Autocannon -3p
Soulreaper cannon -5p
Demonic Axe - 35p
Hellforged Sword - 32p
Lightning Claws -1/-1p
Plaguesword -2p
Power Fist -8p

Doom Siren change d3 => d6
Fleshmetal guns change Assault 2 => Assault 4
Lasher Tendrils change d6 => 6

**Comment by ilaunchbury** [comment]
@Izwor, I'm not sure if you've actually looked at the release as I'm pretty sure all of the changes above except for the Doom Siren are already in it?

**Comment by Rasputinprime** [comment]
If this is the place to add issues, related to the Berzerker power fist issue, the power axe option for the champion is 12 points instead of the new cost of 5.
