### ISSUE TITLE
Imperium - Astra Militarum - Various issues

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#1399]
- [x] Atlas Recovery Tank - Missing 'Recovery Vehicle' ability description.
- [x] Bullgryns
  - Missing default weapon selections.
  - Missing Frag Bombs.
- [x] Hades Breaching Drill Squadron
  - All model profiles are missing/empty.
  - Drill weapon profile is empty.
  - Missing default model selection.
  - Veterans missing weapon constraints.
  - Veterans' equipment should be collective.
  - Sergeant is misspelled.
  - Sergeant's Bolt Pistol should cost 1pt, Plasma Pistol 5pts, Power Fist 10pts.
- [x] Tauros Assault Vehicle - Missing default weapon selection.
- [x] Tauros Venator - Missing default weapon selection.
- [x] Cyclops Demolition Vehicle - Missing model profile.
- [x] Earthshaker Carriage Battery
  - Crew missing weapon constraints.
  - Crew equipment should be collective.
- [x] Heavy Mortar Battery - Crew equipment should be collective.
- [x] Heavy Weapons Squad - Missing minimum 1 on Heavy Weapons.
- [x] Leman Russ Annihilator/Conqueror/Stygies Vanquisher - 'Grinding Advance' ability should be different on these variants, or include their turret weapons.
- [x] Malcador Annihilator - Missing default sponson and demolisher cannon selection.
- [x] Malcador Defender - Missing default sponson selection.
- [x] Malcador Infernus - Missing default sponson and fuel selections.
- [x] Medusa Carriage Battery - Crew equipment should be collective.
- [x] Raiper Laser Destroyer
  - Crew missing weapon constraints.
  - Crew equipment should be collective.
- [x] Tarantula Battery
  - Missing 'Automated Artillery' and 'Immobile' ability descriptions.
  - Missing default weapon selection.
- [x] Aquila Lander - Missing default weapon selection.
- [x] Arvus Lighter - Weapons should be optional, not minimum 1.
- [x] Lightning Strike Fighter - Missing damage table.
- [x] Thunderbolt Heavy Fighter
  - Missing damage table.
  - Missing 'Repair' ability description.
- [x] Macharius (all variants) - Missing second and third row of damage table.
