### ISSUE TITLE
Aeldari - Craftworlds v19 - Bug Tracker

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k#1704]
- [x] Mindshock Pod needs to be -2 LD
- [x] Heavy D-scythe should be Str 12
- [x] Forgeworld units don't have access to relics
- [x] D-Cannon should be S12 and have the rule "this weapon can target units that are not visible to the firer"
- [x] Vibrocannon has an additional new rule, "If this weapon inflicts any damage on an enemy unit, that unit cannot Advance in its next Movement phase unless it can FLY."
- [x] Lasblaster is Assault 4
- [x] Heavy Wraithcannon is S16
- [x] Suncannon is flat 2 dmg
- [x] Voidbringer (Ilic Nightspear's weapon) is now flat 3 dmg
- [x] Executioner is no longer -1 to hit, and is +1S (instead of +2S
- [x] Base points are 15p - Should be 14p with scorpion chainsword (shuriken pistol is free)
- [x] Scorpions claw + scorpion chainsword is 22p - should be 13p (12p for scorpion claw and 1p for chainsword)
- [x] Shuriken pistol and biting blade is 12p - Should be 8p (for the biting blade, pistol is free)
- [x] Shuriken pistol + scorpion chainsword is 2p - should be 1p
- [x] Mirrorswords (should be 4pts)
- [x] Pistol + Executioner (should be 7pts)
- [x] Executioner profile is incorrect. 
- [x] Swooping Hawk PL increments incorrectly #1730 
- [x] Runes of Battle Descriptions incorrect #1729 
- [x] Runes of Battle Ranges incorrect #1723 
- [ ] Check Psytronome of Iyanden availability

**Comment by FarseerVeraenthis** [comment]
Oh yeah... There are moar bugs, I'll list them in this thread
- [ ]  forgeworld units don't have access to relics

**Comment by KalChoedan** [comment]
Howling Banshee Weapon Options are incorrectly costed:
- [ ] Mirrorswords (should be 4)
- [ ] Pistol + Executioner (should be 7)

(Sorry FV I can see you're working on this as I am submitting it)

**Comment by jammie479** [comment]
Autarch with swooping hawks wings the point are wrong.

**Comment by KalChoedan** [comment]
Autarch with Swooping Hawk Wings is correct:
85 (unit)
+6 (Forceshield)
+9 (Fusion Pistol)
+4 (Power Sword)
=104, which is what is reported by Battlescribe.

**Comment by Owlsbane** [comment]
Hemlock Wraithfighter has Spirit Stones as an Ability, not as a Vehicle Upgrade. I think the cost is already integrated, shouldn't cost an additional 10 points for the non-existing Vehicle Upgrade.

**Comment by KalChoedan** [comment]
@Owlsbane That's was FAQd in Index Imperium 1 - all unit abilities that have a corresponding cost in that army's "other wargear" table must be paid in the same way as their weapons. The Community Team have also confirmed this a couple of times on their Facebook page.

You do in fact have to pay the extra 10pts for the Spirit Stones (and the 6pts for the Autarch's Forceshield.)

**Comment by Owlsbane** [comment]
kk, must have missed that one. Thanks for the explanation.

**Comment by Lokust** [comment]
Crimson Hunter exarch weapon options are under the Exarch -> exarch weapons section in the data file, so starcannon cost is presently wrong since it doesn't use the global entry for it.

**Comment by rjn80** [comment]
Scorpion Claw is supposed to be 12 points not 22

**Comment by Lokust** [comment]
rjn80 that was already reported and is in the summary

**Comment by buckeyede06** [comment]
What about other characters and getting relics? For instance the Avatar is a character but can't select a relic. Also is it possible to add the War Lord traits?

**Comment by FarseerVeraenthis** [comment]
I'm of the opinion that named characters have fixed wargear and can't take relics, but I might be wrong... That's why they don't have them at the moment :wink: I'll look into it :+1:

**Comment by alphalas** [comment]
![de0b0acd-22b2-4ef4-95d3-627d2047fa8f](https://user-images.githubusercontent.com/15703066/32415984-22665912-c210-11e7-92e9-621386572c2c.png)

So no, no artifacts for the avatar

**Comment by Phoenix8472** [comment]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** Yes

**Description** Swooping Hawks Power Level for 6+ is incorrect. It jumps by 7PL when it should be +3 PL. 
Psytronome of Iyanden: should be available to all Psykers but is only available to Farseer. Needs Warlock, Spiriteer and Bonesinger adding.

**Comment by buckeyede06** [comment]
I am still unsure, the avatar is not named. The other characters all have a unique name “Karandras”  but the avatar isn’t named and he isn’t even unique. All craftworlds have one according to the lore. Not sure though.

**Comment by alphalas** [comment]
It is unique in the consideration of the tabletop game – imo that’s enough for me to make him count as a named character

**Comment by Phoenix8472** [comment]
Psytronome of Iyanden availability does work correctly for me, I just hadn’t realised it needs the Craftworld attribute selected for each detachment in the list. 
Autarch can take Power Sword and Shard of Anaris when they should be mutually exclusive
