### ISSUE TITLE
T'au Empire - 8th ed Codex effort

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2625]
A general issue tracking update progress for T'au Empire and their new and shiny Codex coming up 2018-03-17.

* [x] Weapon profiles update: d59a185a719a3aadb5f6a8cf2fdad55897ca85c2
* [x] Current unit/weapon/upgrade point costs update: 598cd30a8f2d860834d610889dd68dd4564d3464, entries left (not currently existing/name change):
  * [x] Commanders (normal => XV85 Enforcer, XV8)
  * [x] ~Ethereal on Hover Drone (& removing the option from normal ethereal)~
* [x] Farsight probably gains High-intensity plasma rifle
* [x] Remove no-longer existing entries (Stimulant Injector) (un-crossed per FAQ)
* [x] XV8-02 Iridium upgrade
* [x] Signature Systems
* [x] Septs + Tenets
* [x] Stratagems (for bonus SigSys)
* [x] Warlord Traits
* [x] Implement Commander limitation for Matched-play (max 1 Commander per detachment if `Matched play` selected) [note](https://github.com/BSData/wh40k/issues/2625#issuecomment-382055432)
* [x] Implement Ethereal limitation for Farsight Enclaves (selecting Farsight Enclaves "sept" prohibits taking any Ethereals) [note](https://github.com/BSData/wh40k/issues/2625#issuecomment-382055432)
* [x] Implement Sept limitations when Sept selected (e.g. selecting T'au Sept prohibits taking Farsight)
* [x] Update datasheets:
  * [x] HQ
  * [x] Troops
  * [x] Elites
  * [x] Fast Attack
  * [x] Flyers + Dedicated Transports
  * [x] Heavy Support  + Lords of War
  * [x] Fortifications
* [x] Change over all Ability rules into profiles (except those common)
* [x] Unite Attached Drones abilities
* [x] Add Target Lock profile link to SkyRay

---

For any comments or issues associated with the topic, please open a new issue and mention/link back to this one. This issue shall be used exclusively for progress tracking.

**Comment by superrugdr** [comment]
Remove no-longer existing entries (Stimulant Injector) < shouldn't this option stay there under the FAQ that allow taking profile lost in the codex from the index (same case as for shrikes)

**Comment by alphalas** [comment]
No, because it’s a list item; not an actual wargear item on a datasheet.

**Comment by rider49** [comment]
So, I can take might is right and another warlord trait from the brb?
What about in the rule book where it says on page 186?
I am new to the game and too battlescribe so I know I can be wrong I just
want to be sure one way or the other.

**Comment by Alvirulan** [comment]
@alphalas What do you mean with list item? I do not believe that there is such thing. Codex, Index and brb only describe models and wargear.
Stimulant injector is definitively a wargear item.

**Comment by alphalas** [comment]
My point is it’s not a wargear item specifically on the data sheet; so is not subject to the designer’s commentary

**Comment by Alvirulan** [comment]
Well if look at https://i.redd.it/n3g7779rddyz.jpg and at p46 of Index - Imperium 2 (Commissar), you have a similar example (replace stimulant injector by power axe in this case)

**Comment by amis92** [comment]
Amendments:

* XV86 Coldstar theoretically can replace "high-output burst cannon and/or missile pod with two items from the *Ranged Weapons* and/or *Support Systems* lists" which implies

**Comment by txeptsyip** [comment]
you currently have normal shield drones as being 11 points each they are 10 points each in the codex (it is the special ones that accompany shadowsun that are 11 points each)

**Comment by Kohato** [comment]
@txeptsyip That has been fixed - pending release of a handful of bugfixes.

**Comment by JosephHalter** [comment]
I think MV1 Gun Drones are supposed to have 2 Pulse carabine each. Each Pulse carabine being Assault 2 for a total of 4 shots. Currently they're listed as having Pulse carabine, I don't see it being mentioned that they each have two. Could that be clarified? Thank you.

**Comment by superrugdr** [comment]
the 2 pulse carbine is listed in the wargear section of the datasheet for each unit profile. and you will see 2x pulse carbine on the Mk-1 Gun drone. under "Selections"

**Comment by JosephHalter** [comment]
Sorry to bother you with it, I just don't see it. Maybe it's because I'm using the iOS version and it only shows up on desktop? Or I'm just going blind but I see it neither when view a particular unit or if I print the whole roster:

![2018-03-26 16 24 27](https://user-images.githubusercontent.com/116534/37912710-5b1da586-3113-11e8-955f-9e519f1895ce.png)

![2018-03-26 16 24 08](https://user-images.githubusercontent.com/116534/37912686-4f14268e-3113-11e8-9c21-0fe371da2778.png)

Maybe the issue is with BattleScribe itself and not with the data files.

**Comment by amis92** [comment]
You're using minimal output, so the weapons don't show at all (the profile shows, but it doesn't mean you have one, it means there are some carbines in the unit). Click on the cog symbol, and change `minimal` to `full` :)

**Comment by amis92** [comment]
I've implemented both limits:

* Implement Commander limitation for Matched-play (max 1 Commander per detachment if Matched play selected)
* Implement Ethereal limitation for Farsight Enclaves (selecting Farsight Enclaves "sept" prohibits taking any Ethereals)

But due to the BattleScribe bug https://github.com/BattleScribe/Release/issues/3 they're not yet working, pending BS fix.

**Comment by amis92** [comment]
I've confirmed with Jon that a fix is prepared, will be in next BattleScribe release.
