### ISSUE TITLE
Necrons Codex Update

### ISSUE THREAD

**Issue by Kohato** [BSData/wh40k#2640]
Items of Note:

We have a Codex coming out.  
There is a beta dex leaked and on various sites.
This is a BETA dex, given to the playtesters.
I will not be releasing these changes/points until the codex releases proper.
Do not ask. I will throw you into the sun.

Carry On.

Testing Cat: https://github.com/BSData/wh40k/blob/Necrons-Codex/Necrons.cat

Bugfixes: 100/100 - ALL DONE! BREAK MORE PLEASE!

- [x] Change Tomb Blade Auxilliary to Wargear Choice to match Cryptek
- [x] Heavy Destroyers can be taken in Destroyer unit when 2 total models present
- [x] Un-Hide Relics if Strategem is Chosen, Limit to 1
- [x] Modify Cryptek Movement and Shield Vanes Armor
- [x] Update Lord Profile
- [x] Add Reference Tag to the "ALL" choices.
- [x] Possible Dynastic Code Issue: Select Sautekh, take Hyperlogical, Swap to Mephret, No error
    - Can't fix, this is a BS Bug: https://github.com/BattleScribe/Release/issues/6
- [x] Hide Named HQ based on Dynastic Code

Progress: 100/100 - ALL DONE!

- [x] Points Changes
- [x] Profile Changes
   - [x] HQ
   - [x] Troops
   - [x] Elites
   - [x] Heavy Support
   - [x] Fast Attack
   - [x] Flyers
   - [x] Transports
   - [x] LoW
   - [x] Wargear
- [x] Rules Changes 
- [x] Warlord Traits
   - [x] Random WT Choice vs pre-select Logic
- [x] Artifacts
   - [x] Extra Artifacts Logic
   - [x] Artifacts Dynasty Choice Logic
- [x] C'Tan Powers
   - [x] Random Power Choice vs pre-select Logic
- [x] Dynasties

**Comment by axisofentropy** [comment]
Do it on a branch, then correct and merge it once those leaks are confirmed.

**Comment by Kohato** [comment]
Yes, that is what is being done.

**Comment by alphalas** [comment]
This is for randos, not devs @axisofentropy - something we can point people at like #1706

**Comment by Kohato** [comment]
Codex File is complete - See Please Test on the test branch https://github.com/BSData/wh40k/tree/Necrons-Codex

Will be committed to Main on Friday night at Midnight.

**Comment by joshdeboer** [comment]
Looking good! I did notice that you can add a Heavy Destroyer to a Destroyer unit when there's less than three models and you shouldn't be able to.

**Comment by Kohato** [comment]
Fixed! Ty.
