### ISSUE TITLE
April 2018 Big FAQ updates

### ISSUE THREAD

**Issue by Crowbar90** [BSData/wh40k#2897]
**Imperium - FW Adeptus Astartes**
- [x] Add plasma cannon to Chaplain Venerable Dreadnought
- [x] Add hunter-killer missiles (up to 3) to Relic Leviathan Dreadnought
- [x] Fire Raptor Gunship now costs 280 points base

**Imperium - Legion of the Damned**
~~- [x] Add ability "Saviours from Beyond" to Damned Legionnaires (already done)~~
