### ISSUE TITLE
Chapter Approved 2018 - Finish Adding Custom Character Output, Battle Honors Logic and Output

### ISSUE THREAD

**Issue by mugginns** [BSData/wh40k#4315]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Would it be possible to make it so when you choose the narrative game type you can add Custom Character Options to your warlord? Would be really cool. Would be great if they modify the stat line in the list too.

**Comment by WindstormSCR** [comment]
To expland on the previous comment: for those unfamiliar with the data structure, the main game system file (GST) contains the things that every catalog "sees", while the catalogs are each codex and the stuff within them. however, in the current version of battlescribe, codex .cat files cannot modify or add riders on to .gst entries, only reference them. 

This means it's possible to do the profile adjustments on characters in a roundabout way slightly less than 50% of the time, and weapons maybe 10% of the time, while tripling the linecount the character takes up in the file and increasing the memory burden of the catalog.

As a result it is far easier to just include the table results as abilities, and list them on the character when selected, allowing players to do their own validation for those abilities (example, a shield-captain won't benefit from blademaster nor can he take it).

This may change in the future, but right now is simply the only real option.

**Comment by WindstormSCR** [comment]
Adding a progress tracker for implementation of battle honors and the custom character options in various catalogs.

GST: 
- [ ] Entry ability text
- [ ] Battle Honors Logic
- [ ] Battle Honors Result Text

Catalog Implementation:
Custom Characters:
- [ ] Craftworlds
- [ ] Drukhari
- [ ] Harlequins
- [ ] Chaos Space Marines
- [ ] Daemons
- [ ] Dark Mechanicum
- [ ] Death Guard
- [ ] FW Heretic Astartes
- [ ] FW renegades and heretics
- [ ] Questor Traitoris
- [ ] Thousand Sons
- [ ] Astra Telepathica
- [ ] Custodes
- [ ] Admech
- [ ] Ministorum
- [ ] Astra Militarum
- [ ] Blood Angels
- [ ] Dark Angels
- [ ] Deathwatch
- [ ] FW Adeptus Astartes
- [ ] FW Krieg
- [ ] FW elysians
- [ ] Grey Knights
- [ ] Inquisition
- [ ] Legion of the Damned
- [ ] Assassinorum
- [ ] Imperial Knights
- [ ] Space Marines
- [ ] Space Wolves
- [ ] Necrons
- [ ] Orks
- [ ] Tau
- [ ] GSC
- [ ] Tyranids

**Comment by amis92** [comment]
Sorry, won't have time during holidays, maybe after.

**Comment by Kohato** [comment]
Perhaps we can rename the "Is a custom character/Has Battle Honors" in GST? It feels odd having a sentence as a selection entry.

**Comment by WindstormSCR** [comment]
Its all done!
