### ISSUE TITLE
GK Source Updates

### ISSUE THREAD

**Issue by tekton** [BSData/wh40k#5111]
- [ ] Sources are missing on shared rules for GK
- [ ] Sources are missing on units for GK
- [x] ~~Aircraft keyword re-pass~~ removed in favor of #5220

**Comment by tekton** [comment]
closing in favor of #5233
