### ISSUE TITLE
AIRCRAFT keyword from Big FAQ Spring 2019

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#5220]
This is the state of assigning Aircraft keyword introduced in the Big FAQ Spring 2019:

- [x] Aeldari - Craftworlds
- [x] Aeldari - Drukhari
- [x] ~Aeldari - FW Corsairs~
- [x] ~Aeldari - Harlequins~
- [x] ~Aeldari - Ynnari~
- [x] Chaos - Chaos Space Marines
- [x] ~Chaos - Daemons~
- [x] ~Chaos - Dark Mechanicum~
- [x] ~Chaos - Death Guard~
- [x] Chaos - FW Heretic Astartes
- [x] Chaos - FW Renegade and Heretics
- [x] ~Chaos - Gellerpox Infected~
- [x] ~Chaos - Questor Traitoris~
- [x] ~Chaos - Servants of the Abyss~
- [x] ~Chaos - Thousand Sons~
- [x] ~Chaos - Titanicus Traitoris~
- [x] ~Fallen~
- [x] ~Imperium - Adeptus Astra Telepathica~
- [x] Imperium - Adeptus Custodes
- [x] ~Imperium - Adeptus Mechanicus~
- [x] ~Imperium - Adeptus Ministorum~
- [x] ~Imperium - Adeptus Titanicus~
- [x] Imperium - Astra Militarum
- [x] ~Imperium - Blackstone Fortress~
- [x] Imperium - Blood Angels
- [x] Imperium - Dark Angels
- [x] Imperium - Deathwatch
- [x] ~Imperium - Elucidian Starstriders~
- [x] Imperium - FW Adeptus Astartes
- [x] ~Imperium - FW Death Korps of Krieg~
- [x] Imperium - FW Elysians
- [x] Imperium - Grey Knights
- [x] ~Imperium - Inquisition~
- [x] ~Imperium - Legion of the Damned~
- [x] ~Imperium - Officio Assassinorum~
- [x] ~Imperium - Questor Imperialis~
- [x] ~Imperium - Sisters of Silence~
- [x] Imperium - Space Marines
- [x] Imperium - Space Wolves
- [x] Necrons
- [x] Orks
- [x] T'au Empire
- [x] ~Tyranids - Genestealer Cults~
- [x] ~Tyranids~
- [x] ~Unaligned - Monsters and Gribblies~

*if the catalogue is ~~crossed out~~ it means there are no applicable units*

---

As of this issue creation that's what the gst category usage looks like:

![image](https://user-images.githubusercontent.com/2671396/59602650-8b565400-9107-11e9-986d-f21e848ff104.png)

These catalogues probably can be marked as done, but I'll leave that to every cat owner separately do declare what's actually done for sure.

---
### Notice
When~ implementing this change, please mention this issue in the commit message, along with faction name, so that the links that'll appear here will make sense (and not 10 commits "aircraft keyword #5220"). Also please don't say "fix/fixes/close/closes #5220" as that'll close this issue.

**Comment by DrTobogganMD** [comment]
Did these back when it came out. Crons are good to go.

**Comment by amis92** [comment]
@alphalas @CrusherJoe @flakpanda @WindstormSCR @acebaur 

Any chance we can get the remaining done soon?

* Imperium - Astra Militarum (@alphalas)
* Imperium - Blood Angels (@alphalas)
* Imperium - Deathwatch (@acebaur)
* Imperium - FW Death Korps of Krieg (@CrusherJoe @alphalas)
* Imperium - FW Elysians (@alphalas)
* Imperium - Space Marines (@flakpanda @WindstormSCR)
* Imperium - Space Wolves (@CrusherJoe)

**Comment by Mad-Spy** [comment]
I've finished these off. All now complete.
