### ISSUE TITLE
Publications cleanup

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#5233]
First mentioned here: https://github.com/BSData/wh40k/issues/4977#issuecomment-486126247

Currently publications are "each catalogue on their own", with a lot of duplication in catalogues and between them *and* between them and game system. Naming styles vary, overall - not a great experience. Since 2.02 we now have publications extracted as standalone entities. I propose we do a solid cleanup.

Tasks so far:
- [x] Unify naming and style (e.g. BRB, Warhammer 40k Rulebook, Warhammer 40,000 The Rules => one thing)
- [x] Deduplicate publications within catalogues
- [x] Make GST contain publications that are used in at least two catalogues (and others on a case by case basis)
- [ ] Fix GST publications (e.g. Stronghold, Planetfall, and others no longer existing)
- [ ] Pass-through of catalogues to correct references

**Comment by DrTobogganMD** [comment]
Amis - It appears some profiles are linked to the Stronghold Assault publication. We don't have any alternative publication for those profiles.  The game mode won't work anymore but we may want to leave the pub in for now.

**Comment by amis92** [comment]
@DrTobogganMD how are we standing with Stronghold/Planetstrike? I think there has been some newer publication with terrain rules (like a chapter approved/tournament pack or something?). Am I right?

**Comment by amis92** [comment]
Since no one seems to care, by my decree this issue is to be closed.

I've done as much as I cared to be bothered.

**Comment by amis92** [comment]
Scripts I've used: https://gist.github.com/amis92/ffa4500d12aa712c0524cc748cf09c91
