### ISSUE TITLE
Munitorum Field Manual 2019 Edition progress

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6086]
This tracks only point updates from MFM as part of #6054:

- [x] Aeldari - Craftworlds
- [x] Aeldari - Drukhari
- [x] Aeldari - FW Corsairs
- [x] Aeldari - Harlequins
- [x] Aeldari - Ynnari
- [x] Chaos - Chaos Space Marines
- [x] Chaos - Daemons
- [x] Chaos - Dark Mechanicum (no changes)
- [x] Chaos - Death Guard
- [x] Chaos - FW Heretic Astartes
- [x] Chaos - FW Renegade and Heretics (no changes)
- [x] Chaos - Gellerpox Infected (no changes)
- [x] Chaos - Questor Traitoris
- [x] Chaos - Servants of the Abyss
- [x] Chaos - Thousand Sons
- [x] Chaos - Titanicus Traitoris (no changes)
- [x] Fallen
- [x] Imperium - Adeptus Astra Telepathica
- [x] Imperium - Adeptus Custodes
- [x] Imperium - Adeptus Mechanicus
- [x] Imperium - Adeptus Ministorum
- [x] Imperium - Adeptus Titanicus
- [x] Imperium - Astra Militarum
- [x] Imperium - Blackstone Fortress
- [x] Imperium - Blood Angels
- [x] Imperium - Dark Angels
- [x] Imperium - Deathwatch
- [x] Imperium - Elucidian Starstriders
- [x] Imperium - FW Adeptus Astartes
- [x] Imperium - FW Death Korps of Krieg
- [x] Imperium - FW Elysians
- [x] Imperium - Grey Knights
- [x] Imperium - Inquisition
- [x] Imperium - Legion of the Damned
- [x] Imperium - Officio Assassinorum
- [x] Imperium - Questor Imperialis
- [x] Imperium - Sisters of Silence
- [x] Imperium - Space Marines
- [x] Imperium - Space Wolves
- [x] Necrons
- [x] Orks
- [x] T'au Empire
- [x] Tyranids - Genestealer Cults
- [x] Tyranids
- [x] Unaligned - Monsters and Gribblies
- [x] Game System entries

**Comment by amis92** [comment]
## Request

@BSData/data-authors-wh40k If you're starting the work on a catalogue, please comment here to let others know it's actually in progress.

**Comment by amis92** [comment]
I'm currently working on Tau.

**Comment by tag8833** [comment]
I'll get Orks Done either tonight or Tomorrow morning.

**Comment by amis92** [comment]
Forge World / T'au Empire / Ranged Weapons section lists *Heavy burst cannon* but I'm assuming an inevitable errata that changes it's name to *Swiftstrike burst cannon* since that's the name they were using for their version since at least a year in updated datasheets (e.g. Barracuda, Fire Support Hammerhead), and it also (Swiftstrike version) has no entry, and has the same cost (55pts).

**Comment by tag8833** [comment]
Ork Codex Big Shoota is 5 pts, while FW Big Shoota is 6.  To account for this discrepancy, I've created a separate entry, and linked all FW units to use the new entry.

**Comment by FarseerVeraenthis** [comment]
Drukhari, Harlequins & Corsairs are done. However, there is no "Other Wargear" section for either Drukhari or Harlequins, so those ponits have not been changed in the file from what they previously were.

**Comment by FarseerVeraenthis** [comment]
Imperium - Legion of the Damned are not included in the MFM. I have marked them as complete.

**Comment by amis92** [comment]
@alphalas I guess you're doing BA? It'd seem the honors of closing this issue and pushing the release will fall upon you, then :)
