### ISSUE TITLE
BA catchall bugrep

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#6131]
- [x] Assault bolters still at 10p instead of 8p
- [x] Boltstorm gauntlet still at 22p instead of 12p
- [x] Flamestorm cannon still at 30p instead of 25p
- [x] Grav-cannon and grav-amp still at 28p instead of 20p
- [x] Grav-gun still at 12p instead of 10p
- [x] Inferno pistol still at 7p instead of 9p
- [x] Special issue boltgun still at 2p instead of 0p
- [x] Typhoon missile launcher still at 38p instead of 32p
- [x] Dreadnought combat weapon still at 30p instead of 20p
- [x] Lightning Claw still at 8p instead of 6p (check the paired variant too)
- [x] Combat shield still at 4p instead of 1p
- [x] Intercessors of any kind are missing options: Thunderhammer, Hand flamer.
- [x] "Honoured of Baal" option missing for successor chapters.
- [x] Malakim Phoros doesn’t hide unless lamenters
- [x] Cyclone Missile Launcher cost not updated
- [x] Relic constraint OR should be AND
- [x] Mephiston is incorrectly max 0 in Roster when there are zero Legends Mephiston instead of 1.
- [x] Astorath can only take 2 litanies. Should be able to take 3.
- [x] DC Intercessor squad weapons aren't incrementing in cost.
- [x] The Savage Echos wording contains "... performs at her work intervention...". It should be "...performs a Heroic Intervention...".

**Comment by jmkk11** [comment]
Auxhillary Grenade Launchers for Intercessors should be 1 pt

**Comment by sfPanzer-BnC** [comment]
@jmkk11 they are 1p in the current version

**Comment by jmkk11** [comment]
List of bugs i found in 1.4.0 Imperium Blood Angels - issues #6156

**Comment by jmkk11** [comment]
> 
> 
> @jmkk11 they are 1p in the current version

are you sure? im running on cat 100 for BA and it hasn't got the points cost for them

**Comment by sfPanzer-BnC** [comment]
@jmkk11 Looking at 100 too and it's there

**Comment by jmkk11** [comment]
![image](https://user-images.githubusercontent.com/37638462/70533169-cb4b4080-1b58-11ea-8414-6b8ea30e3b8e.png)

hmm super weird

**Comment by sfPanzer-BnC** [comment]
@jmkk11 
![image](https://user-images.githubusercontent.com/58656211/70533643-ca66de80-1b59-11ea-8f65-44638433a2ab.png)

**Comment by jmkk11** [comment]
where are you getting that **Chapter** option panzer, it's not showing for me

**Comment by sfPanzer-BnC** [comment]
@jmkk11 it's part of the update

**Comment by jmkk11** [comment]
ahaa right, my bscribe was pulling from the release repo (Y)
