### ISSUE TITLE
AM/DK/EDT catchall bugrep 

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#6135]
- [x] Avenger Strike Fighter defensive heavy stubber cost should be 0, not 4.
- [x] Field Commander should be a selection on parent, not NFOC
- [x] Lascannons, 
- [x] Astropath, 
- [x] Mortars, 
- [x] Punishers 
- [x] Although it's a Character with Regiment Keyword, neither Marshall nor field officer can use a heirloom of conquest If Chosen as Warlord.
- [x] Lord Commissar should be able to take 2 items from the Melee list, but can only take 1. Taking two gives a validation error (Link validation bug)
