### ISSUE TITLE
Space Marines FAQ/Errata Tracker

### ISSUE THREAD

**Issue by flakpanda** [BSData/wh40k#632]
- [x] Pages 12 and 208 – Wrist-mounted grenade launcher
Change the AP value to read ‘-1’.
- [x] Page 26 – Company Veterans, Wargear Options
Change the second bullet point to read: ‘• Any model may replace their bolt pistol with a storm shield or an item from the Melee Weapons or Pistols list.’
- [x] Page 29 – Scout Squad, Concealed Positions
Change this ability to read: ‘Concealed Positions: When you set up this unit during deployment, it can be set up anywhere on the battlefield that is more than 9" from the enemy deployment zone and any enemy models.’
- [x] Pages 34, 42, 124 and 207 – Melta bomb
Change the Abilities text to read: ‘You can re-roll failed wound rolls for this weapon if the target is a Vehicle.’
- [x] Pages 40, 41 and 207 – Grenade harness
Change the AP value to read ‘-1’.
- [x] Page 43 – Inceptor Squad
Change the Crushing Charge rule to read: ‘Roll a D6 each time a model from this unit finishes
a charge move within 1" of an enemy unit; on a 6, the enemy unit suffers a mortal wound.’
- [x] Pages 48 and 208 – Twin heavy flamer
Change the Type to read ‘Heavy 2D6’.
- [x] Page 56 – Stalker, Damage Table
Change the third value under ‘Remaining W’ to read ‘1-2’.
- [x] Page 78 – Chaplain Grimaldus, Unmatched Zeal
Change the first sentence of this ability to read: ‘If you roll a hit roll of 6+in the Fight phase for a model
in a friendly Black Templars unit that is within 6" of Chaplain Grimaldus, that model can immediately make another close combat attack using the same weapon.’ 
- [x] Page 203 – Space Marine Points Values, Lords of War
Add the following text beneath ‘Points Per Model’: ‘(Including Wargear)’
- [x] Page 204 – Space Marine Points Values, Other Wargear
Add the following line: ‘Ironclad assault launchers | 5’

**Comment by Crowbar90** [comment]
I already updated the profiles that are in the GST, I'm marking them now.
