### ISSUE TITLE
Imperium - Grey Knights - Brother Captains and Smite QoL

### ISSUE THREAD

**Issue by tekton** [BSData/wh40k#650]
File/Catalogue: Imperium - Grey Knights.cat (v3)

BattleScribe version: 2.01.

Platform: All

Dropbox: No

Description:
- [x] Brother-Captain missing Rites of Banishment
- [x] Brother-Captain Stern missing Zone of Banishment
- [x] Kaldor Draigo fixes
- [x] Multiple units missing Smite in abilities (this is really a QoL thing)
* - [x] HQ
* - [x] Troops
* - [x] Elites
* - [x] Fast Attack
* - [x] Heavy Support

**Comment by tekton** [comment]
I've got a lot of these worked out, but I'm flying out and didn't want to forget again.

**Comment by skaigh** [comment]
Stern is also missing 'The Strands of Fate'
