### ISSUE TITLE
Aeldari - Craftworlds - FAQ Updates

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#654]
- [x] Melta bomb range reduced to 4"
- [x] Serpent Shield wording changed
- [x] Starcannon & Twin Starcannon damage changed to D3
