### ISSUE TITLE
AM Library File creation

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#6752]
To simplify editing duplicate units, the following AM units need to be put into a Library file then linked to from AM/EDT/DKOK:

- [ ] Officer of the fleet
- [ ] valkyries
- [ ] tauros
- [ ] Tauros Venator
- [ ] Vulture
- [ ] Vendetta
- [ ] tarantula
- [ ] cyclops
- [ ] thunderbolt
- [ ] lightning
- [ ] avenger
- [ ] Master of Ordinance
- [ ] Rapier Lasdes
- [ ] hydras
- [ ] Tank Commander
- [ ] Griffon
- [ ] Hades
- [ ] Hellhounds
- [ ] Salamander Scout
- [ ] Styges Thunderer
- [ ] Basilisks
- [ ] Armageddon Medusa
- [ ] Colossus bombard
- [ ] quad launcher
- [ ] heavy mortar
- [ ] atlas
- [ ] centaur light
- [ ] earthshaker carriages
- [ ] gorgon
- [ ] malcador annihilator
- [ ] malcador defender
- [ ] malcador heavy
- [ ] malcador infernus
- [ ] medusa
- [ ] styges destroyer
- [ ] arkurian stormblade
- [ ] macharius (all types)
- [ ] trojan
- [ ] Baneblade
- [ ] Shadowsword
- [ ] stormsword
