### ISSUE TITLE
FW Adeptus Astartes progress tracker

### ISSUE THREAD

**Issue by Crowbar90** [BSData/wh40k#721]
I'm putting this here to track my progress through Imperial Armour - Index: Forces of the Adeptus Astartes. 

- [x] Preliminary work
  - [x] Weapon and equipment profiles and entries
- [x] Adeptus Astartes Battle Armour
  - [x] Deimos Pattern Relic Predator
  - [x] Deimos Pattern Vindicator Laser Destroyer
  - [x] Infernum Pattern Razorback
  - [x] Relic Land Raider Proteus
  - [x] Land Raider Helios
  - [x] Land Raider Prometheus
  - [x] Land Raider Achilles
  - [x] Relic Sicaran Battle Tank
  - [x] Relic Sicaran Venator Tank Destroyer
  - [x] Relic Sicaran Punisher Assault Tank
- [x] Adeptus Astartes Heavy Armour
  - [x] Relic Spartan Assault Tank
  - [x] Relic Typhon Heavy Siege Tank
  - [x] Relic Cerberus Heavy Tank Destroyer
  - [x] Relic Fellblade Super-heavy Tank
  - [x] Relic Falchion Super-heavy Tank Destroyer
  - [x] Relic Mastodon Super-heavy Siege Transport
- [x] Adeptus Astartes Dreadnoughts
  - [x] Mortis Dreadnought
  - [x] Siege Dreadnought
  - [x] Contemptor Mortis Dreadnought
  - [x] Chaplain Venerable Dreadnought
  - [x] Relic Contemptor Dreadnought
  - [x] Relic Deredeo Dreadnought
  - [x] Relic Leviathan Dreadnought
- [x] Adeptus Astartes Strike Craft
  - [x] Land Speeder Tempest
  - [x] Relic Javelin Attack Speeder
  - [x] Xiphon Interceptor
  - [x] Storm Eagle Assault Gunship
  - [x] Storm Eagle Assault Gunship - ROC Pattern
  - [x] Fire Raptor Assault Gunship
  - [x] Caestus Assault Ram
  - [x] Thunderhawk Assault Gunship
  - [x] Thunderhawk Transporter
  - [x] Sokar Pattern Stormbird
- [x] Adeptus Astartes Battlefield Support
  - [x] Damocles Command Rhino
  - [x] Whirlwind Hyperios
  - [x] Relic Whirlwind Scorpius
  - [x] Rapier Carrier
  - [x] Tarantula Sentry Gun
  - [x] Tarantula Air Defence Battery
  - [x] Lucius Pattern Dreadnought Drop Pod
  - [x] Deathstorm Drop Pod
  - [x] Castellum Stronghold
- [x] Integrate FAQ
  - [x] Page 4, Relic rule
  - [x] Page 9, Relic Land Raider Proteus, Heavy Armour ability
  - [x] Page 14, Relic Sicaran Venator Tank Destroyer, unit description
  - [x] Page 20, Relic Fellblade Super-heavy Tank, wargear options
  - [x] Page 21, Relic Falchion Super-heavy Tank Destroyer, wargear options
  - [x] Pages 24 and 26, Mortis Dreadnought and Contemptor Mortis Dreadnought, wargear options
  - [x] Page 29, Relic Deredeo Dreadnought, Atomantic Pavaise ability
  - [x] Page 32, Relic Javelin Attack Speeder, Gravitic Augur Haze ability
  - [x] Page 32, Relic Javelin Attack Speeder, wargear options
  - [x] Page 36, Fire Raptor Assault Gunship, wargear options
  - [x] Page 43, Rapier Carrier, Space Marine Gunners ability
  - [x] Page 43, Rapier Carrier, wargear options
  - [x] Page 45, Lucius Pattern Dreadnought Drop Pod and Deathstorm Drop Pod, Immobile ability
  - [x] Page 56, Lord High Commander Carab Culln and Lugft Huron, Teleport Strike ability
  - [x] Page 58, Lord Asterion Moloc, wounds
  - [x] Page 64, Harath Shen, Master Apothecary of the Salamanders Chapter, save
  - [x] Page 69, Hecaton Aiakos, wargear
  - [x] Pages 72 and 75, add Cyclone missile launcher
  - [x] Page 76, Heavy neutron pulse array, damage
- [x] Imperial Armour Character Appendix
  - [x] Lord High Commander Carab Culln
  - [x] Lugft Huron, The Tyrant of Badab
  - [x] Armenneus Valthex
  - [x] Captain Corien Sumatris
  - [x] Arch-Centurion Carnac Commodus
  - [x] Lord Asterion Moloc
  - [x] Chaplain Ivanus Enkomi
  - [x] Magister Sevrin Loth
  - [x] Tyberos the Red Wake
  - [x] Chaplain Dreadnought Titus
  - [x] Lieutenant Commander Anton Narvaez
  - [x] Captain Tarnus Vale
  - [x] Lias Issodon
  - [x] Malakim Phoros
  - [x] Captain Mordaci Blaylock
  - [x] Captain Pellas Mir'san
  - [x] Bray'arth Ashmantle
  - [x] Harath Shen
  - [x] Ahazra Redth
  - [x] High Chaplain Thulsa Kane
  - [x] Captain Silas Alberec
  - [x] Knight-Captain Elam Courbray
  - [x] Vaylund Cal
  - [x] Captain Zhrukhal Androcles
  - [x] Hecaton Aiakos
- [x] Cleanup work
  - [x] Characters refactor (removing duplicate and unnecessary abilities)
    - [x] Lord High Commander Carab Culln
    - [x] Lugft Huron, The Tyrant of Badab
    - [x] Armenneus Valthex
    - [x] Captain Corien Sumatris
    - [x] Arch-Centurion Carnac Commodus
    - [x] Lord Asterion Moloc
    - [x] Chaplain Ivanus Enkomi
    - [x] Magister Sevrin Loth
    - [x] Tyberos the Red Wake
    - [x] Chaplain Dreadnought Titus
    - [x] Lieutenant Commander Anton Narvaez
    - [x] Captain Tarnus Vale
    - [x] Lias Issodon
    - [x] Malakim Phoros
    - [x] Captain Mordaci Blaylock
    - [x] Captain Pellas Mir'san
    - [x] Bray'arth Ashmantle
    - [x] Harath Shen
    - [x] Ahazra Redth
    - [x] High Chaplain Thulsa Kane
    - [x] Captain Silas Alberec
    - [x] Knight-Captain Elam Courbray
    - [x] Vaylund Cal
    - [x] Captain Zhrukhal Androcles
    - [x] Hecaton Aiakos
