### ISSUE TITLE
Astra Militarum Errata/FAQ Progress Tracker

### ISSUE THREAD

**Issue by ThomasEll** [BSData/wh40k#722]
- [x] Maximum of one \<Regiment\> Company Command Squad in a detachment for each \<Regiment\> Officer (Company Commander or Platoon Commander) in that detachment.
- [x] Maximum of one Militarum Tempestus Command Squad in a detachment for each Tempestor Prime in that detachment.
- [x] Ratlings movement characteristic to 5"
- [x] Ratlings Shoot and Scarper rule to read: ‘Shoot Sharp and Scarper: Immediately after making a shooting attack (other than firing Overwatch), this unit can move as if it were the Movement phase (though it cannot Advance as part of this move).’ 
- [x] Abilities text of Demolisher Cannon to read: ‘When attacking units with 5 or more models, change
this weapon’s Type to Heavy D6.’
