### ISSUE TITLE
Adeptus Ministorum errata/FAQ Progress Tracker

### ISSUE THREAD

**Issue by ThomasEll** [BSData/wh40k#723]
- [x] Celetine
    - [x] Add the following text: ‘Only one of this unit may be included in your army.’
    - [x] Change the first sentence of the Saintly Blessing ability to read: ‘At the start of each of your turns, you can pick a friendly Adepta Sororitas unit within 6" of Celestine that has the Acts of Faith ability and perform an Act of Faith with it.’ 
- [x] Imagifier change the first sentence of the Simulacrum Imperialis ability to read: ‘Roll a D6 at the start of each of your turns; on a 4+ you can pick a friendly <Order> unit within 6" of this model that has the Acts of Faith ability and perform an Act of Faith with it.’ 
- [x] Battle Sisters Squad, add the following wargear option: 'The Sister Superior may take a weapon from the Melee Weapons List'
- [x] Celestian Squad, add the following wargear option: 'The Celestian Superior may take a weapon from the Melee Weapons List'
- [x] Retributor Squad 
    - [x] Change the Retributor Superior's leadership characteristic to 8
    - [x] Add the following wargear option: 'The Retributor Superior may take a weapon from the Melee Weapons List'
- [x] Dominion Squad 
    - [x] Vanguard, in between the first and second sentences and the following: ‘This unit cannot end this move within 9" of any enemy models.’
    - [x] Add the following wargear option: 'The Dominion Superior may take a weapon from the Melee Weapons List'
- [x] Hand Flamer, change the type to be Pistol D3
- [x] Storm Bolters, change the points value to be 2
- [x] Twin-Multi Melta, change the abilities text to read: ‘If the target is within half range of this weapon, roll two dice when inflicting damage with it and discard the lowest result.’
