### ISSUE TITLE
Imperium - FW AM Units adding

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#728]
- [x] Aquilla
- [x] Atlas
- [x] Salamander Command
- [x] Centaur
- [x] Gryphonne Chimera
- [x] Trojan
- [x] Artemia Hellhound
- [x] Armageddon Basilisk
- [x] Armageddon Medusa
- [x] Earthshaker Battery
- [x] Earthshaker Carrage Battery
- [x] hydra battery
- [x] Russ Annilator
- [x] Russ Conqueror
- [x] Russ Styges Vanq
- [x] Malcador Annilator
- [x] malcador Defender
- [x] Malcador Heavy Tank
- [x] Malcador Infernus
- [x] Manticore Battery
- [x] Medusa Carrage Battery
- [x] Sabre Weapons Battery
- [x] Sentinel powerlifters
- [x] Avenger
- [x] Colossus Bombard
- [x] Cyclops
- [x] Griffon
- [x] Hades
- [x] Heavy mortar
- [x] Heavy quad launcher
- [x] Lightning
- [x] Raiper
- [x] Salamander Scout
- [x] Styges Thunderer
- [x] Styges Destroyer
- [x] Arkurian Stormblade
- [x] Arkurian Stormhammer
- [x] Arkurian Stormsword
- [x] Crassus
- [x] Dominus
- [x] Gorgon
- [x] Mach heavy tank
- [x] mach Omega
- [x] Mach Vanquisher
- [x] Mach Vulkan
- [x] Marauder
- [x] Marauder Destroyer
- [x] Minotaur
- [x] Praetor
- [x] Valdor
- [x] Arvus
- [x] Tarantaula
- [x] Tauros
- [x] Tauros Venator
- [x] Thunderbolt
- [x] Vendetta
- [x] Vulture
- [x] Fortress walls
- [x] Primaris Redoubt

**Comment by Kuzifer** [comment]
Shadowsword has wrong Damage Value for Volcano Cannon, D3 needs to be 2D6.

**Comment by GenWilhelm** [comment]
Fortress Walls and Primus Redoubt are already in the GST, I'll check them off.

**Comment by OllPersson** [comment]
@Kuzifer that is fixed in #791 (AMv34)

**Comment by jigoralpsi** [comment]
It seems that Marauder Destroyer is missing points and stats on dorsal twin heavy bolter.

**Comment by f1r3warr10r** [comment]
How do I generate AM list with FW flyers without adding additional slot tax?

**Comment by GenWilhelm** [comment]
@f1r3warr10r, see our wiki page on how to create a Detachment from multiple catalogues:
[BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions](https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions)

**Comment by alphalas** [comment]
@f1r3warr10r, 1, the flyers that are checked so far are in the file, but not useable yet; when this bugrep closes is when it will all go live. 2, For cross-faction (soup) armies, you do need to add a child detachment- it's a limitation of the BS program itself. We made the cats the way we did to make the most of the capabilities of the app, without making everything bloated and harder to load on low memory devices.

**Comment by f1r3warr10r** [comment]
Thank you so much brother, but where can I find fw:astra militarum? I don't see where I can choose vultures and the like. Do you know the answer? Should  I can contact you directly if it is more appropriate?

**Comment by alphalas** [comment]
As of right now, the only ones you can use are in Elysians- when I finish AM they'll be in that cat too

**Comment by f1r3warr10r** [comment]
I have A LOT of guard flyers. Will they all be available eventually on BScribe? Does someone else you other faction FW?

**Comment by f1r3warr10r** [comment]
Thank you. You have done a good job.

**Comment by alphalas** [comment]
But yes, to answer you all the FW flyers will be in the regular AM cat once I finish it

**Comment by f1r3warr10r** [comment]
Cool, can't wait! Thanks for your dedication, I really do appreciate it.

**Comment by lotlp** [comment]
Two weeks later, alphalas tried adding the CRASSUS ARMOURED ASSAULT TRANSPORT and drowned in memes. RIP.

**Comment by alphalas** [comment]
had an issue with data loss and general computer nonsense; it'll be finished tomorrow (hopefully)

**Comment by f1r3warr10r** [comment]
Where will I find vultures, thunderbolts, vendettas, avengers and lightnings?


On August 1, 2017, at 11:33 PM, Jon Kissinger <notifications@github.com> wrote:


had an issue with data loss and general computer nonsense; it'll be finished tomorrow (hopefully)

**Comment by alphalas** [comment]
Like I said, it will be in AM - but probably won't go live until I finish everything.

**Comment by f1r3warr10r** [comment]
Sorry, I misunderstood. I really, really grateful that you do these. Do you do any other?


On August 1, 2017, at 11:42 PM, Jon Kissinger <notifications@github.com> wrote:


Like I said, it will be in AM - but probably won't go live until I finish everything.

**Comment by capitaladot** [comment]
Derp... I selected the Macharius looking for the absent Malcador.

**Comment by alphalas** [comment]
@capitalidot I just pushed a fix for that - it'll be in next release

**Comment by f1r3warr10r** [comment]
I still cannot find any flyers for astra militarum besides Valkyries. Am I doing something wrong? My files are up to date as of this time.


On August 1, 2017, at 11:53 PM, Jon Kissinger <notifications@github.com> wrote:


@capitalidot I just pushed a fix for that - it'll be in next release

**Comment by f1r3warr10r** [comment]
I just read your last message so please disregard my last.


On August 1, 2017, at 11:51 PM, "Austin C." <notifications@github.com> wrote:


@alphalas<https://github.com/alphalas> Malcador Heavy Tank entry appears hosed. Charges points for all possible weapon options, allows no selections.

**Comment by lotlp** [comment]
The data is not out yet, please be patient.

**Comment by f1r3warr10r** [comment]
Sorry, your response didn't show up in my email. Waiting patiently. Thanks, sorry I'm an idiot

**Comment by capitaladot** [comment]
The Malcador Heavy Tank appears to still be jacked up... Two front weapons
without costs, no PL, etc.
