### ISSUE TITLE
Amendments to FW Death Korps of Krieg

### ISSUE THREAD

**Issue by DeathKorps** [BSData/wh40k#743]
Imperium - FW Death Korps of Krieg

BattleScribe version: 2.01.

**Reorganization**
- [x] Move "Death Korps Field Officer" from "uncategorized" to "HQ"
- [x] Move "Death Korps Infantry Squad" from "uncategorized" to "Troops"
- [x] Move "Death Korps Heavy Weapons Squad" from "uncategorized" to "Heavy Support"
- [x] Move "Mars Alpha Pattern Leman Russ" from "uncategorized" to Heavy Support

**Changes**
- [x] Add power level of 4 to "Death Korps Heavy Weapons Squad"
- [x] Add point value of 23 to "Death Korps Field Officer"
- [x] Add stats for Hades Breaching Drill and Melta Cutter
- [x] Add stats for Veterans (DKoK Engineers) with the Hades Breaching Drill Squad
- [x] Add stats for Death Riders, Ride masters, and Krieg Mount (Savage Claws Melee attack) on Death rider squad, death rider squad commander, 
- [x] Add stats to Centaur Assault Carrier

- [x] Set defaults

**Comment by CrusherJoe** [comment]
@DeathKorps I have a question: when you say "add stats" may I ask if you are including Inline or Profile summaries? When I view the roster with Inline Profiles turned on I can see the stats.

**Comment by CrusherJoe** [comment]
Okay the latest commit should fix everything listed -- please open a new report if you find anything else that's not right. Thank you for your help!
