### ISSUE TITLE
Chaos - FW Heretic Astartes - Imperial Armour Errata v1.1

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#810]
- [x] Pages 13 and 14 – Hellforged Land Raider Proteus and Hellforged Land Raider Achilles, Containment Breach
Change the third sentence of this ability to read:
'Each unit within 6" suffers D6 mortal wounds unless it is a Psyker, in which case it suffers 2D3 mortal wounds.'

- [x] Pages 33 and 34 – Chaos Storm Eagle Assault Gunship and Chaos Fire Raptor Assault Gunship, Damage Tables
Change the third value under 'BS' to read '5+'

- [x] Add Ferrum Infernus Dreadnought

- [x] Add Emperor's Children Sonic Dreadnought

- [x] Add Chaos Vindicator Laser Destroyer

[Source](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_Chaos_ver_1.1.pdf)

**Comment by Drachnyen** [comment]
Hello!

Did the the 1.0 Errata changes get implemented?   (I didn't see an issue for it - maybe I missed it)
I am still seeing old descriptions and costs prior to errata.

**Comment by ilaunchbury** [comment]
They should be in 1.0.31 and above? There wasn't a specific issue, I did them as part of something else. They're showing correctly on my release version.

If you think there's something missing, let me know.

**Comment by Drachnyen** [comment]
@ilaunchbury Everything looks good from a description point of view - Good job ;)
(I think I had old datafiles or misread the text)

I did find one thing missing: 

- [ ] Page 72 - Chaos Decimator - Soul Burner Petard - Increase points to 60

**Comment by ilaunchbury** [comment]
Oops! I'll do it alongside these changes.

**Comment by Drachnyen** [comment]
Glad I can help and thanks for the updates - Much appreciated!
