### ISSUE TITLE
Imperium - Astra Militarum - Imperial Armour Errata v1.0

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#812]
- [x] Page 10 – Gryphonne Pattern Chimera
Change the description to read:
'A Gryphonne Pattern Chimera is a single model equipped with a twin heavy bolter, a heavy bolter and two lasgun arrays.'

- [x] Page 10 – Gryphonne Pattern Chimera, Wargear Options
Add the following bullet point to this model's wargear options:
'• This model may replace its twin heavy bolter with an autocannon.'

- [x] Pages 16, 17, 18 and 26 – Earthshaker Carriage Battery, Heavy Mortar Battery, Heavy Quad Launcher Battery, Medusa Carriage Battery, Artillery Battery
Change this to read:
'When this unit is set up on the battlefield, all models are set up in unit coherency. From that point onwards, all the Artillery models are treated as one unit and all the Guardsmen Crew are treated as another. Guardsmen Crew may only be chosen as a target in the Shooting phase if they are the closest visible enemy unit to the firer.'

- [x] Page 27 – Sabre Weapons Battery, Defence Searchlight
Change this to read:
'If this model has a defence searchlight, at the start of your Shooting phase it may select a single enemy unit within 48" and line of sight. One friendly <Regiment> Infantry or <Regiment> Sabre Weapons Battery unit adds 1 to any hit rolls that target the chosen unit until the end of the Shooting phase. A single unit cannot benefit from multiple Defence Searchlights.'

- [x] Page 27 – Rapier Laser Destroyer, Imperial Guard Crew
Change this ability to read:
'When this unit is set up on the battlefield, all models are set up in unit coherency. From that point onwards, the Rapier Laser Destroyer is treated as one unit and all the Guardsmen Crew are treated as another. Guardsmen Crew may only be chosen as a target in the Shooting phase if they are the closest visible enemy unit to the firer.'

- [x] Page 27 – Rapier Laser Destroyer, Guardsmen Crew
Change the Guardsmen Crew characteristics profile so
that it reads:
M WS BS S T W A Ld Sv
'6" 4+ 4+ 3 3 1 1 6 5+'

- [x] Page 30 – Arkurian Pattern Stormblade, Description and Wargear Options
Change the description to read:
'An Arkurian Pattern Stormblade is a single model equipped with a plasma blastgun, a heavy bolter and adamantium tracks.'
Add the following to the wargear options:
'• This model may take either two sponsons or four sponsons – each sponson is equipped with a lascannon and either a twin heavy bolter or twin heavy flamer.'

- [x] Pages 39 and 113 – Macharius vulcan mega-bolter
Change this weapon's ability to read:
'If this model does not move during its Movement phase, in your next Shooting phase, change this weapon's Type to Heavy 30 until the end of the turn.'

- [x] Pages 40 and 41 – Marauder Bomber and Marauder Destroyer, Abilities
Add the following ability:
'Supersonic: Each time this model moves, first pivot it on the spot up to 90° (this does not contribute to how far the model moves) and then move the model straight forwards. Note that it cannot pivot again after the initial pivot. When this model Advances, increase its Move characteristic by 20" until the end of the phase – do not roll a dice.'

- [x] Page 110 – Astra Militarum Points Values
Change the points per model value for the Leman Russ Conqueror to read '132'.

[Source](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf)
