### ISSUE TITLE
Imperiam - FW Death Korps of Krieg - Imperial Armour Errata v1.0

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#813]
- [x] Page 56 – Wargear, Heavy Weapons
Change the fourth bullet point to read:
'• Twin heavy stubber'

- [x] Page 60 – Death Korps Grenadier Storm Squad
Add the following Characteristics profile for a Death Korps Grenadier Weapons Team:
M WS BS S T W A Ld Sv
'6" 3+ 3+ 3 3 2 2 6 4+'

- [x] Page 60 – Death Korps Grenadier Storm Squad, Wargear Options
Change the fourth bullet point to read:
'• Up to two Grenadiers may replace their hot-shot lasguns with either a heavy stubber or an item from the Death Korps of Krieg Special Weapons list.'
Add the following bullet point:
'• Two other Grenadiers may form a Death Korps Grenadier Weapons Team with a heavy flamer.'

- [x] Page 62 – Death Korps of Krieg Storm Chimera
Change the description to read:
'A Death Korps of Krieg Storm Chimera is a single model equipped with a turret autocannon, a heavy bolter and two lasgun arrays.'

- [x] Page 63 – Death Korps Combat Engineer Squad,
Wargear Options
Add the following bullet point:
'• One Engineer may take a demolition charge.'

- [x] Page 69 – Death Korps Leman Russ Mars-Alpha Battle Tanks, Grinding Advance
Change the second sentence of this ability to read:
'The following weapons are turret weapons: Conqueror battle cannon, battle cannon, Eradicator nova cannon, Exterminator autocannon, Vanquisher battle cannon, Demolisher cannon, Executioner plasma cannon, Punisher gatling cannon, twin-lascannon and co-axial heavy stubber.'

- [x] Page 116 – Death Korps of Krieg Points Values, Death Korps of Krieg Ranged Weapons
Add the following line:
'Twin heavy stubber | 8 points'

- [x] Page 117 – Death Korps of Krieg Points Values, Death Korps of Krieg Other Wargear
Change the second column header to read 'Points per Item'
Add the following line:
'Storm armour and mine plough | 10 points'

- [x] Page 118 – Death Korps of Krieg Ranged Weapons
Add the following line:
Weapon Range Type S AP D Abilities
'Twin heavy stubber 36" Heavy 6 4 0 1 -'

[Source](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf)
