### ISSUE TITLE
Imperium - FW Elysians - Imperial Armour Errata v1.0

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#814]
- [x] Page 71 – Elysian Drop Troops Army List
Change the final sentence of the first paragraph to read:
'Models that have the Aeronautica Imperialis keywords on their datasheets replace them in all instances with Elysian Drop Troops.'
Change the second sentence of the second paragraph to read:
'Tauros units on the list opposite will also benefit from the Aerial Drop ability.'

- [x] Page 72 – Wargear, Ranged Weapons
Add '• Boltgun'.

- [x] Page 74 – Elysian Drop Trooper Squad, Wargear Options
Change the fifth bullet point to read:
'The Sergeant may exchange his laspistol for a lasgun or a plasma pistol.'

- [x] Pages 74 and 120 – Plasma Pistol – Supercharged
Change the Damage characteristic of this profile to read '2'.

- [x] Pages 74, 75 and 120 – Breacher charge
Add the following to the end of the weapon's ability:
'Each breacher charge can only be used once per battle.'

- [x] Page 75 – Elysian Veteran Squad, Wargear Options
Change the last bullet point to read:
'The Sergeant may exchange his laspistol for a lasgun or an option from the Elysian Drop Troops Ranged Weapons list.

[Source](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf)
