### ISSUE TITLE
Chaos - Renegades & Heretics - Imperial Armour Errata v1.0

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#815]
- [x] Page 81 – Renegades and Heretics Army List
Add the following units to the list of those that can have the Renegades and Heretics keywords:
- [x] Armageddon Pattern Medusa
 Imperial Armour – Index: Forces of the Astra Militarum
- [x] Earthshaker Carriage Battery
 Imperial Armour – Index: Forces of the Astra Militarum
- [x] Medusa Carriage Battery
 Imperial Armour – Index: Forces of the Astra Militarum
- [x] Macharius Heavy Tank
 Imperial Armour – Index: Forces of the Astra Militarum
- [x] Macharius Omega
 Imperial Armour – Index: Forces of the Astra Militarum
- [x] Macharius Vanquisher
 Imperial Armour – Index: Forces of the Astra Militarum
- [x] Macharius Vulcan
 Imperial Armour – Index: Forces of the Astra Militarum

- [x] Page 81 – Renegades and Heretics Army List
Change the first paragraph to read:
'There are a number of Astra Militarum datasheets that can also be used by Renegades and Heretics models – presented in the box on the left. Those that do replace the \<Regiment> keyword on their datasheet in all instances with Renegades and Heretics and the Imperium keyword with Chaos. In addition, they lose they Astra Militarum Faction keyword. Renegades and Heretics Transports whose datasheets say that they can transport Astra Militarum Infantry models can instead transport an equivalent number of Renegades and Heretics Infantry models. If an Astra Militarum unit does not appear on the list, it cannot be from the Renegades and Heretics, and so cannot have the Renegades and Heretics Faction keyword.'

- [x] Page 82 – Renegades and Heretics Discipline, Creeping Terror
Change the second sentence to read:
'Choose an enemy unit within 12", if that unit takes a Morale test in this battle round, subtract D3 from its Leadership characteristic until the end of the battle round.'

- [x] Page 83 – Renegade Commander, Keywords
Add 'Character'.

- [x] Page 83 – Malefic Lord, Keywords
Add '\<Chaos Covenant>'.

- [x] Page 86 – Renegade Mutant Rabble, Curse of Mutation
Change the last sentence to read:
'On a 5 or 6, add 1 to the unit's Toughness.'

- [x] Page 86 – Chaos Spawn, Keywords
Change 'Infantry' to 'Beast'.

- [x] Page 89 – Renegade Enforcer, Keywords
Add 'Character'.

- [x] Page 91 – Renegade Ogryn Beast Handlers, Keywords
Add the following line:
'(Chaos Mauler Hounds): Infantry, \<Chaos Covenant>, Chaos Mauler Hounds'

- [x] Page 121 – Renegades and Heretics Points Values
Change the models per unit value of the Renegade Command Squad to read '4-14'.
Change the models per unit value of Renegade Ogryn Brutes to read '3-12'.
Change the models per unit value of Renegade Plague Ogryns to read '3-9'.

[Source](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf)
