### ISSUE TITLE
DKOK addition per FAQ

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#862]
- [x] Arkurian Pattern Stormblade
- [x] Atlas Recovery Tank
- [x] Baneblade
- [x] Centaur Light Carrier
- [x] Cyclops Demolition Vehicle
- [x] Earthshaker Carriage Battery
- [x] Gorgon Heavy Transporter
- [x] Macharius Heavy Tank
- [x] Macharius Omega
- [x] Macharius Vanquisher
- [x] Macharius Vulcan
- [x] Malcador Annihilator
- [x] Malcador Defender
- [x] Malcador Heavy Tank
- [x] Malcador Infernus
- [x] Medusa Carriage Battery
- [x] Minotaur Artillery Tank
- [x] Stygies Destroyer Tank Hunter
- [x] Shadowsword
- [x] Stormsword
